### ISSUE TITLE
9.1.2

### ISSUE THREAD

**Issue by bharv410** [liamcottle/SnapLib#1]
Hey you said you are working on a fix but you do you have any timeline? Any way others could help?

**Comment by liamcottle** [comment]
Heya, I've got everything working from 9.1.2.0 in my app [Casper](http://bit.ly/casperapp)

Just haven't made had the time to put it all on here.

I'm not sure if I want to put it all on GitHub, as I believe the Snapchat team are now looking at how we are using their APIs by looking at our code.

**Comment by Snowlav** [comment]
@liamcottle there's a private gitlab, the owner of the php snapchat repo opened it.
Do you have skype?

**Comment by bharv410** [comment]
@liamcottle @Snowlav Hey could you all help me get access to the fix? : ) 
I have a gitlab account too.

**Comment by hako** [comment]
@liamcottle @Snowlav can you let me in on the fix too, I also have GitLab. I might have something you guys should know about.

**Comment by krruzic** [comment]
Writing a snapchat library in Python right now (I had been using a ported version of php-snapchat before). Wondering I could get in on this fix too?

**Comment by jerry317** [comment]
Hi @liamcottle check your email, I'm Jerry.
