### ISSUE TITLE
version of Snapchat 

### ISSUE THREAD

**Issue by k41ed** [liamcottle/SnapLib#3]
{"message":"You\u0027re using a version of Snapchat or operating system that\u0027s no longer supported. Please upgrade your device\u0027s operating system and update to the newest app version to use Snapchat. Thanks!","logged":false}

**Comment by liamcottle** [comment]
[This repo no longer works.](https://github.com/liamcottle/SnapLib#snaplib-no-longer-works-i-might-release-a-new-java-library-in-the-future)
